version: 2.1
jobs:
  start_bot:
    working_directory: /src
    docker:
      - image: node:19.2.0
    steps:
      - checkout

      # Install dependency-dependency yang dibutuhkan
      - run:
          name: Install semua dependency
          command: npm install
      
      # Jalanin bot nya
      - run:
          name: Mulai botnya
          command: npm start

workflows:
  version: 2

  mulai_dan_tes:
    jobs:
      - start_bot